### ISSUE TITLE
Result notification email failed to send

### ISSUE THREAD

**Issue by mgawroncisco** [CiscoTestAutomation/pyats#169]
I'm getting such error at the end of my job run:
`2022-07-05T10:03:56: %EASYPY-INFO: Sending report email...
2022-07-05T10:03:56: %EASYPY-INFO: Missing SMTP server configuration, or failed to reach/authenticate/send mail. Result notification email failed to send.
2022-07-05T10:03:58: %EASYPY-INFO: Done!`

How to add some configuration? And where to put it?

**Comment by stevedhn** [comment]
Hi, you can check how to configure your email notification here:
https://pubhub.devnetcloud.com/media/pyats/docs/easypy/email.html
In order to configure Easypy to use your own SMTP host, update the following fields in pyATS Configuration’s block:
https://pubhub.devnetcloud.com/media/pyats/docs/configuration/index.html#pyats-configuration
