### ISSUE TITLE
is it possible to use console connection?

### ISSUE THREAD

**Issue by hh7843175** [CiscoTestAutomation/pyats#20]
Hey there, 

i find nothing about the list of protocols which is supported by pyATS for connecting to a device. I want to login a device through the console port, is it possible or i have to write my own connection class for pyATS? I mean something like this [[+](https://pubhub.devnetcloud.com/media/pyats/docs/connections/class.html)]

Again, 
Thanks in advance, specially @jeaubin :heart: ;)

**Comment by jeaubin** [comment]
Hi @hh7843175, 

For interacting with the device we have a package named Unicon which supports console and ssh.

You can find the documentation here: https://pubhub.devnetcloud.com/media/pyats-packages/docs/unicon/ 

Here an example on how to connect.

https://pubhub.devnetcloud.com/media/pyats-packages/docs/unicon/user_guide/connection.html#sample-testbed-file-for-a-single-nxos-device 

When using it in a script you can pass the testbed file like this

```
easypy <job file> -testbed_file <tb.yaml>
```

Then in your testscript you can do.

```
 class common_setup(aetest.CommonSetup):
     """ Common Setup section """

     @aetest.subsection
     def connect(self, testbed):   <-- Notice here, I passed a testbed argument, this is your tb object
         """ Common Setup subsection """
         for device in testbed:
             device.connect()
```


This will use the "a" connection of your yaml file

```
    connections:
      defaults:
        class: 'unicon.Unicon'
      a:
        protocol: telnet               <--- 
        ip: 10.64.70.11
        port: 2042
```

Let me know if you got other question with connecting to your devices. 

Btw you can reach us at pyats-support-ext@cisco.com

**Comment by siming85** [comment]
what type of device is this?

for specific behaviors such as connecting and issuing enter after connection... you might need to write a plugin.

it is possible to set "command" field I think for testbed yaml so it uses your specific minicom command, but to get the states to behave correctly... it's still plugin based

**Comment by mdear** [comment]
There's a workaround that may help you, as per our [documentation](https://pubhub.devnetcloud.com/media/pyats-packages/docs/unicon/user_guide/connection.html#prompt-recovery-usage):

```
from unicon import Connection
dev = Connection(hostname='R2',
                 start=['minicom'],      <-- or ['screen /dev/ttyUSB0 9600']
                 username='admin',
                 tacacs_password=r'Cisc0123',
                 prompt_recovery=True)
```

After the connection is attempted, when it would normally time out (because it is not default behavior to press Enter after connecting), the prompt recovery feature sends a sequence of characters (including Enter) in an attempt to get a recognizable prompt.

Another option is to write your own plugin that defines a connection [provider ](https://pubhub.devnetcloud.com/media/pyats-packages/docs/unicon/developer_guide/plugins.html#connections-provider) that customizes the process of logging into a device by pressing Enter initially.

**Comment by hh7843175** [comment]
@siming85 I don't know what is exactly, I have just done some research.
@mdear Thanks for introducing this trick ;). It works for me.
