### ISSUE TITLE
Aetest processor for failed assertions

### ISSUE THREAD

**Issue by SergiyBeno** [CiscoTestAutomation/pyats#41]
Hello folks,
I have set of tests with various assertions. After each test execution, we get a `TestResult` object that contains info about result code, name, tims. But there is no info about error/fail reason in case of test failure. 
I have found a temporary workaround using `@aetest.processor` feature (https://pubhub.devnetcloud.com/media/pyats/docs/aetest/processors.html?highlight=processors). But it has one drawback - it catches only exceptions. That means that I have to replace all assert statements with a custom implementation of the Exception class and raise exceptions in case some condition was not met. That is nasty and wrong approach. 
So my question is - how can I get a failed assertion message in a more friendly way? 
Maybe I'm missing something obvious?

**Comment by simingy** [comment]
when you do `self.failed()` or `self.passed()`, the API it self also supports, reason, and data

`self.failed('because I needed to fail`, data = {})
https://pubhub.devnetcloud.com/media/pyats/docs/aetest/results.html#

if you are using `assert` i think that's not being filled - but if you use result apis it would help.

does that answer the question?

**Comment by SergiyBeno** [comment]
Thanks, @simingy! It did the trick!
