### ISSUE TITLE
Upload pyATS results to TRADe from docker container

### ISSUE THREAD

**Issue by SET-SKYNET** [CiscoTestAutomation/pyats#49]
@simingy 
Hello, Siming Yuan!
Please advise me how can I upload pyATS results to TRADe from docker container?

**Comment by bastell** [comment]
Hi,
Sorry for the long delay.

The pyATS Docker image has the external version of pyATS, which does not support uploading to TRADe. What you are looking for is a Docker image with the internal version of pyATS. This is easy to build using the pyATS Image Builder.
https://github.com/CiscoTestAutomation/pyats-image-builder

You can make a YAML file something like this:
```yaml
tag: myimage:latest
packages:
  - ats[full]
pip-config: |
  [global]
  format = columns
  no-cache-dir = false
  trusted-host =
      pypi.python.org
      pyats-pypi.cisco.com
  index-url = http://pyats-pypi.cisco.com/simple
  disable-pip-version-check = 1
```

This will build a new Docker image with the internal version of pyATS installed, which supports uploading to TRADe via REST api calls.

**Comment by SET-SKYNET** [comment]
@bastell 
Uploading to TRADe via REST api calls is exactly what I am looking for.
You mean use _Log Uploader_ for it or some other API?
If other, please give me a link to the documentation of this API for uploading to TRADe via REST! =)

**Comment by bastell** [comment]
Hi,
Uploading to TRADe via REST happens automatically when using the internal version of pyATS, and is unsupported when using the external version of pyATS. The important difference is to install `ats` from the internal PYPI server, instead of `pyats` from the public PYPI server. The image `ciscotestautomation/pyats` has external `pyats` installed, so you will have to make your own image with `ats` installed. This is very straightforward using the pyATS Image Builder.
